apiVersion: apps/v1
kind: Deployment
metadata:
  name: PaymentManagement
  labels:
    app: PaymentManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PaymentManagement
  template:
    metadata:
      labels:
        app: PaymentManagement
    spec:
      containers:
        - name: PaymentManagement
          image: username/PaymentManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5